// This file is auto-generated by train_model.py. Do not edit manually.

class CropPricePredictor {
  /// Predicts the price of a crop per kg (in INR) based on inputs.
  /// 
  /// Parameters:
  /// - [cropIndex]: 0 for Wheat, 1 for Rice, 2 for Maize, 3 for Cotton, 
  ///   4 for Potato, 5 for Tomato, 6 for Onion, 7 for Sugarcane.
  /// - [month]: 1 (Jan) to 12 (Dec)
  /// - [temperature]: current temperature in Celsius
  /// - [rainfall]: monthly rainfall in mm
  /// - [humidity]: relative humidity in percentage (0 - 100)
  static double predict({
    required int cropIndex,
    required int month,
    required double temperature,
    required double rainfall,
    required double humidity,
  }) {
    switch (cropIndex) {
      case 0:
        return _predictWheat(
          month: month,
          temperature: temperature,
          rainfall: rainfall,
          humidity: humidity,
        );
      case 1:
        return _predictRice(
          month: month,
          temperature: temperature,
          rainfall: rainfall,
          humidity: humidity,
        );
      case 2:
        return _predictMaize(
          month: month,
          temperature: temperature,
          rainfall: rainfall,
          humidity: humidity,
        );
      case 3:
        return _predictCotton(
          month: month,
          temperature: temperature,
          rainfall: rainfall,
          humidity: humidity,
        );
      case 4:
        return _predictPotato(
          month: month,
          temperature: temperature,
          rainfall: rainfall,
          humidity: humidity,
        );
      case 5:
        return _predictTomato(
          month: month,
          temperature: temperature,
          rainfall: rainfall,
          humidity: humidity,
        );
      case 6:
        return _predictOnion(
          month: month,
          temperature: temperature,
          rainfall: rainfall,
          humidity: humidity,
        );
      case 7:
        return _predictSugarcane(
          month: month,
          temperature: temperature,
          rainfall: rainfall,
          humidity: humidity,
        );
      default:
        return 0.0;
    }
  }

  static double _predictWheat({
    required int month,
    required double temperature,
    required double rainfall,
    required double humidity,
  }) {
    if (rainfall <= 249.9858) {
      if (temperature <= 29.8758) {
        if (month <= 3.5000) {
          if (rainfall <= 29.4065) {
            if (temperature <= 15.0836) {
              return 50.6095;
            } else {
              return 39.6944;
            }
          } else {
            if (temperature <= 14.5583) {
              return 33.5552;
            } else {
              return 29.8979;
            }
          }
        } else {
          if (month <= 6.5000) {
            if (rainfall <= 28.9840) {
              return 29.2477;
            } else {
              return 20.3969;
            }
          } else {
            if (rainfall <= 30.6850) {
              return 37.1566;
            } else {
              return 26.3161;
            }
          }
        }
      } else {
        if (rainfall <= 29.7583) {
          if (temperature <= 36.0203) {
            if (humidity <= 52.7671) {
              return 51.6717;
            } else {
              return 48.8139;
            }
          } else {
            if (month <= 6.0000) {
              return 38.9271;
            } else {
              return 47.8245;
            }
          }
        } else {
          if (month <= 3.5000) {
            if (rainfall <= 146.7843) {
              return 36.3899;
            } else {
              return 41.0059;
            }
          } else {
            if (month <= 6.5000) {
              return 26.5975;
            } else {
              return 33.6960;
            }
          }
        }
      }
    } else {
      if (temperature <= 30.3326) {
        if (month <= 3.5000) {
          if (temperature <= 15.2157) {
            if (humidity <= 40.9229) {
              return 49.1183;
            } else {
              return 45.4247;
            }
          } else {
            if (temperature <= 24.8094) {
              return 40.2076;
            } else {
              return 45.9720;
            }
          }
        } else {
          if (month <= 6.5000) {
            if (temperature <= 25.2360) {
              return 27.7862;
            } else {
              return 31.5863;
            }
          } else {
            if (temperature <= 24.9319) {
              return 35.2604;
            } else {
              return 39.4438;
            }
          }
        }
      } else {
        if (month <= 3.5000) {
          if (temperature <= 31.8513) {
            if (month <= 1.5000) {
              return 56.3190;
            } else {
              return 49.2300;
            }
          } else {
            if (temperature <= 33.3988) {
              return 58.2067;
            } else {
              return 54.8337;
            }
          }
        } else {
          if (month <= 6.5000) {
            if (rainfall <= 343.4455) {
              return 37.9435;
            } else {
              return 36.0482;
            }
          } else {
            if (temperature <= 30.6089) {
              return 48.9715;
            } else {
              return 45.7261;
            }
          }
        }
      }
    }
  }

  static double _predictRice({
    required int month,
    required double temperature,
    required double rainfall,
    required double humidity,
  }) {
    if (rainfall <= 75.0139) {
      if (month <= 10.5000) {
        if (month <= 7.5000) {
          if (temperature <= 16.7301) {
            if (humidity <= 65.3720) {
              return 67.5203;
            } else {
              return 64.6854;
            }
          } else {
            if (temperature <= 36.2849) {
              return 50.6731;
            } else {
              return 66.3421;
            }
          }
        } else {
          if (temperature <= 17.9350) {
            if (humidity <= 63.8256) {
              return 73.6978;
            } else {
              return 79.6830;
            }
          } else {
            if (temperature <= 36.9084) {
              return 64.9884;
            } else {
              return 78.9895;
            }
          }
        }
      } else {
        if (temperature <= 14.3831) {
          if (temperature <= 11.0691) {
            return 50.5275;
          } else {
            return 56.4363;
          }
        } else {
          if (temperature <= 32.0194) {
            if (temperature <= 23.3798) {
              return 42.7711;
            } else {
              return 39.0898;
            }
          } else {
            if (rainfall <= 61.7483) {
              return 44.7813;
            } else {
              return 44.2391;
            }
          }
        }
      }
    } else {
      if (month <= 10.5000) {
        if (temperature <= 17.0690) {
          if (month <= 7.5000) {
            if (month <= 1.5000) {
              return 38.9231;
            } else {
              return 45.5837;
            }
          } else {
            if (rainfall <= 188.8371) {
              return 56.9622;
            } else {
              return 54.1450;
            }
          }
        } else {
          if (month <= 7.5000) {
            if (temperature <= 36.8552) {
              return 34.9898;
            } else {
              return 44.8190;
            }
          } else {
            if (temperature <= 36.9696) {
              return 42.4907;
            } else {
              return 54.6761;
            }
          }
        }
      } else {
        if (temperature <= 37.1069) {
          if (temperature <= 17.2992) {
            if (temperature <= 14.1268) {
              return 35.8000;
            } else {
              return 33.4727;
            }
          } else {
            if (temperature <= 31.9286) {
              return 27.3208;
            } else {
              return 30.3721;
            }
          }
        } else {
          if (rainfall <= 404.4720) {
            if (rainfall <= 182.0450) {
              return 36.4719;
            } else {
              return 34.0829;
            }
          } else {
            if (month <= 11.5000) {
              return 42.2532;
            } else {
              return 38.4293;
            }
          }
        }
      }
    }
  }

  static double _predictMaize({
    required int month,
    required double temperature,
    required double rainfall,
    required double humidity,
  }) {
    if (rainfall <= 299.6369) {
      if (rainfall <= 36.2188) {
        if (month <= 8.5000) {
          if (temperature <= 33.5474) {
            if (month <= 5.5000) {
              return 35.2769;
            } else {
              return 41.3257;
            }
          } else {
            if (month <= 2.5000) {
              return 41.5523;
            } else {
              return 48.9983;
            }
          }
        } else {
          if (rainfall <= 23.9831) {
            if (temperature <= 10.9852) {
              return 40.4448;
            } else {
              return 32.0247;
            }
          } else {
            if (temperature <= 35.2809) {
              return 25.8452;
            } else {
              return 33.7423;
            }
          }
        }
      } else {
        if (month <= 8.5000) {
          if (month <= 5.5000) {
            if (temperature <= 34.1642) {
              return 23.6550;
            } else {
              return 29.2073;
            }
          } else {
            if (temperature <= 34.3037) {
              return 28.3473;
            } else {
              return 34.4837;
            }
          }
        } else {
          if (month <= 11.5000) {
            if (temperature <= 14.0240) {
              return 23.6956;
            } else {
              return 19.4355;
            }
          } else {
            if (temperature <= 33.6391) {
              return 23.7331;
            } else {
              return 28.8710;
            }
          }
        }
      }
    } else {
      if (month <= 8.5000) {
        if (month <= 5.5000) {
          if (temperature <= 33.9729) {
            if (temperature <= 14.0625) {
              return 41.0571;
            } else {
              return 31.5177;
            }
          } else {
            if (rainfall <= 302.9028) {
              return 30.6229;
            } else {
              return 41.0056;
            }
          }
        } else {
          if (temperature <= 34.2187) {
            if (temperature <= 13.8859) {
              return 48.5846;
            } else {
              return 38.5432;
            }
          } else {
            if (temperature <= 36.3078) {
              return 47.0728;
            } else {
              return 48.8058;
            }
          }
        }
      } else {
        if (month <= 11.5000) {
          if (temperature <= 32.8195) {
            if (temperature <= 14.2712) {
              return 31.8428;
            } else {
              return 25.0589;
            }
          } else {
            if (humidity <= 75.4556) {
              return 31.3325;
            } else {
              return 33.0290;
            }
          }
        } else {
          if (temperature <= 14.9994) {
            if (rainfall <= 445.1773) {
              return 41.6134;
            } else {
              return 40.7574;
            }
          } else {
            if (temperature <= 28.8718) {
              return 30.4299;
            } else {
              return 36.4347;
            }
          }
        }
      }
    }
  }

  static double _predictCotton({
    required int month,
    required double temperature,
    required double rainfall,
    required double humidity,
  }) {
    if (rainfall <= 199.9345) {
      if (rainfall <= 23.6938) {
        if (month <= 8.5000) {
          if (temperature <= 22.5621) {
            if (temperature <= 13.4356) {
              return 112.5236;
            } else {
              return 99.2058;
            }
          } else {
            if (rainfall <= 12.8781) {
              return 107.3091;
            } else {
              return 81.3693;
            }
          }
        } else {
          if (temperature <= 15.7650) {
            return 138.4788;
          } else {
            if (temperature <= 37.3214) {
              return 117.5017;
            } else {
              return 133.3723;
            }
          }
        }
      } else {
        if (temperature <= 17.9761) {
          if (month <= 2.5000) {
            if (humidity <= 73.7721) {
              return 66.1545;
            } else {
              return 59.8607;
            }
          } else {
            if (month <= 11.5000) {
              return 84.3669;
            } else {
              return 61.2932;
            }
          }
        } else {
          if (month <= 2.5000) {
            if (rainfall <= 120.9144) {
              return 49.6101;
            } else {
              return 56.4104;
            }
          } else {
            if (temperature <= 33.1404) {
              return 63.1268;
            } else {
              return 75.7682;
            }
          }
        }
      }
    } else {
      if (temperature <= 18.2865) {
        if (month <= 2.5000) {
          if (rainfall <= 474.7801) {
            if (temperature <= 17.8941) {
              return 88.1479;
            } else {
              return 101.5617;
            }
          } else {
            return 74.4520;
          }
        } else {
          if (month <= 11.5000) {
            if (month <= 8.5000) {
              return 109.6912;
            } else {
              return 128.6088;
            }
          } else {
            if (rainfall <= 233.6546) {
              return 94.7976;
            } else {
              return 83.3854;
            }
          }
        }
      } else {
        if (month <= 2.5000) {
          if (temperature <= 33.0786) {
            if (temperature <= 22.7878) {
              return 75.1947;
            } else {
              return 64.9868;
            }
          } else {
            if (temperature <= 38.0539) {
              return 76.1222;
            } else {
              return 88.9532;
            }
          }
        } else {
          if (month <= 11.5000) {
            if (month <= 8.5000) {
              return 89.0842;
            } else {
              return 105.6241;
            }
          } else {
            if (temperature <= 37.7266) {
              return 67.0863;
            } else {
              return 89.8470;
            }
          }
        }
      }
    }
  }

  static double _predictPotato({
    required int month,
    required double temperature,
    required double rainfall,
    required double humidity,
  }) {
    if (rainfall <= 187.7272) {
      if (temperature <= 28.6632) {
        if (rainfall <= 20.9415) {
          if (month <= 3.5000) {
            if (temperature <= 23.4685) {
              return 15.4240;
            } else {
              return 19.4489;
            }
          } else {
            if (month <= 9.0000) {
              return 21.9030;
            } else {
              return 25.4427;
            }
          }
        } else {
          if (month <= 1.5000) {
            if (humidity <= 71.3759) {
              return 17.9125;
            } else {
              return 20.3907;
            }
          } else {
            if (month <= 4.5000) {
              return 12.7875;
            } else {
              return 16.0009;
            }
          }
        }
      } else {
        if (month <= 10.5000) {
          if (month <= 1.5000) {
            if (humidity <= 35.8169) {
              return 22.4684;
            } else {
              return 23.6791;
            }
          } else {
            if (month <= 4.5000) {
              return 17.0049;
            } else {
              return 20.1351;
            }
          }
        } else {
          if (rainfall <= 20.3178) {
            if (humidity <= 75.2148) {
              return 33.3759;
            } else {
              return 34.1972;
            }
          } else {
            if (temperature <= 31.4877) {
              return 25.7477;
            } else {
              return 23.9053;
            }
          }
        }
      }
    } else {
      if (temperature <= 27.7277) {
        if (month <= 10.5000) {
          if (month <= 1.5000) {
            if (temperature <= 22.3637) {
              return 25.0611;
            } else {
              return 27.9203;
            }
          } else {
            if (month <= 4.5000) {
              return 17.3573;
            } else {
              return 21.8500;
            }
          }
        } else {
          if (temperature <= 22.9110) {
            if (temperature <= 12.7567) {
              return 28.1138;
            } else {
              return 23.7460;
            }
          } else {
            if (rainfall <= 225.3441) {
              return 25.6960;
            } else {
              return 27.8478;
            }
          }
        }
      } else {
        if (month <= 10.5000) {
          if (month <= 1.5000) {
            if (temperature <= 33.3667) {
              return 35.2205;
            } else {
              return 32.8822;
            }
          } else {
            if (month <= 4.5000) {
              return 22.2750;
            } else {
              return 27.5310;
            }
          }
        } else {
          if (temperature <= 27.9463) {
            return 28.4867;
          } else {
            if (humidity <= 50.6124) {
              return 31.8328;
            } else {
              return 32.9958;
            }
          }
        }
      }
    }
  }

  static double _predictTomato({
    required int month,
    required double temperature,
    required double rainfall,
    required double humidity,
  }) {
    if (rainfall <= 250.6190) {
      if (rainfall <= 30.4767) {
        if (temperature <= 32.7694) {
          if (humidity <= 47.0789) {
            if (humidity <= 45.3991) {
              return 40.1888;
            } else {
              return 31.9035;
            }
          } else {
            if (month <= 6.0000) {
              return 51.7089;
            } else {
              return 44.0611;
            }
          }
        } else {
          if (month <= 5.5000) {
            if (month <= 3.5000) {
              return 68.1710;
            } else {
              return 65.9304;
            }
          } else {
            if (temperature <= 35.4762) {
              return 62.0914;
            } else {
              return 46.9287;
            }
          }
        }
      } else {
        if (temperature <= 32.1459) {
          if (month <= 5.5000) {
            if (month <= 2.5000) {
              return 31.6106;
            } else {
              return 37.6851;
            }
          } else {
            if (month <= 8.5000) {
              return 25.5477;
            } else {
              return 31.9429;
            }
          }
        } else {
          if (month <= 5.5000) {
            if (month <= 2.5000) {
              return 39.4768;
            } else {
              return 47.2581;
            }
          } else {
            if (month <= 8.5000) {
              return 32.0081;
            } else {
              return 40.2552;
            }
          }
        }
      }
    } else {
      if (month <= 5.5000) {
        if (temperature <= 32.0747) {
          if (month <= 2.5000) {
            if (temperature <= 11.9965) {
              return 55.3422;
            } else {
              return 44.2060;
            }
          } else {
            if (temperature <= 16.7039) {
              return 59.0044;
            } else {
              return 50.6892;
            }
          }
        } else {
          if (month <= 2.5000) {
            if (rainfall <= 384.2812) {
              return 53.0402;
            } else {
              return 56.6119;
            }
          } else {
            if (humidity <= 81.5929) {
              return 65.5481;
            } else {
              return 67.9746;
            }
          }
        }
      } else {
        if (month <= 8.5000) {
          if (temperature <= 31.5488) {
            if (temperature <= 12.2004) {
              return 44.0819;
            } else {
              return 34.6718;
            }
          } else {
            if (temperature <= 33.8147) {
              return 41.5375;
            } else {
              return 43.8725;
            }
          }
        } else {
          if (temperature <= 31.9615) {
            if (temperature <= 11.9764) {
              return 55.3167;
            } else {
              return 43.5827;
            }
          } else {
            if (rainfall <= 294.4042) {
              return 57.4480;
            } else {
              return 54.3680;
            }
          }
        }
      }
    }
  }

  static double _predictOnion({
    required int month,
    required double temperature,
    required double rainfall,
    required double humidity,
  }) {
    if (rainfall <= 224.5985) {
      if (rainfall <= 27.4107) {
        if (temperature <= 29.9313) {
          if (month <= 4.5000) {
            if (rainfall <= 18.2877) {
              return 41.6176;
            } else {
              return 46.0182;
            }
          } else {
            if (month <= 7.5000) {
              return 27.8373;
            } else {
              return 36.0255;
            }
          }
        } else {
          if (month <= 5.0000) {
            if (rainfall <= 19.8626) {
              return 57.6149;
            } else {
              return 52.3211;
            }
          } else {
            if (month <= 7.5000) {
              return 37.6974;
            } else {
              return 47.1608;
            }
          }
        }
      } else {
        if (temperature <= 29.9302) {
          if (month <= 4.5000) {
            if (month <= 1.5000) {
              return 26.0274;
            } else {
              return 31.5244;
            }
          } else {
            if (month <= 7.5000) {
              return 20.8778;
            } else {
              return 26.1071;
            }
          }
        } else {
          if (month <= 4.5000) {
            if (month <= 1.5000) {
              return 34.0167;
            } else {
              return 39.1123;
            }
          } else {
            if (month <= 7.5000) {
              return 26.7009;
            } else {
              return 32.6463;
            }
          }
        }
      }
    } else {
      if (temperature <= 28.8811) {
        if (month <= 4.5000) {
          if (month <= 1.5000) {
            if (temperature <= 15.0307) {
              return 39.1287;
            } else {
              return 35.2257;
            }
          } else {
            if (temperature <= 15.0831) {
              return 46.4421;
            } else {
              return 41.1575;
            }
          }
        } else {
          if (month <= 7.5000) {
            if (temperature <= 15.0349) {
              return 31.5003;
            } else {
              return 28.1404;
            }
          } else {
            if (temperature <= 14.9732) {
              return 39.0511;
            } else {
              return 34.6637;
            }
          }
        }
      } else {
        if (month <= 4.5000) {
          if (month <= 1.5000) {
            if (rainfall <= 261.4881) {
              return 45.2697;
            } else {
              return 47.4807;
            }
          } else {
            if (temperature <= 30.1927) {
              return 47.0823;
            } else {
              return 54.8001;
            }
          }
        } else {
          if (month <= 7.5000) {
            if (temperature <= 29.9610) {
              return 30.9852;
            } else {
              return 36.8397;
            }
          } else {
            if (temperature <= 29.9948) {
              return 39.4649;
            } else {
              return 46.4235;
            }
          }
        }
      }
    }
  }

  static double _predictSugarcane({
    required int month,
    required double temperature,
    required double rainfall,
    required double humidity,
  }) {
    if (rainfall <= 90.1594) {
      if (month <= 3.5000) {
        if (temperature <= 21.8233) {
          if (temperature <= 18.9147) {
            if (month <= 1.5000) {
              return 5.7899;
            } else {
              return 6.1170;
            }
          } else {
            if (rainfall <= 48.3733) {
              return 5.2474;
            } else {
              return 5.5600;
            }
          }
        } else {
          if (temperature <= 34.8920) {
            if (temperature <= 24.8296) {
              return 4.9698;
            } else {
              return 4.3734;
            }
          } else {
            if (humidity <= 91.7032) {
              return 5.2255;
            } else {
              return 4.8995;
            }
          }
        }
      } else {
        if (temperature <= 20.1363) {
          if (month <= 9.5000) {
            if (temperature <= 10.7701) {
              return 8.1019;
            } else {
              return 7.5142;
            }
          } else {
            if (temperature <= 11.8708) {
              return 8.6488;
            } else {
              return 9.1153;
            }
          }
        } else {
          if (month <= 9.5000) {
            if (temperature <= 35.1643) {
              return 5.7859;
            } else {
              return 6.5056;
            }
          } else {
            if (temperature <= 35.0735) {
              return 6.9649;
            } else {
              return 7.9260;
            }
          }
        }
      }
    } else {
      if (month <= 3.5000) {
        if (temperature <= 20.0974) {
          if (rainfall <= 248.8565) {
            if (temperature <= 11.9027) {
              return 4.4432;
            } else {
              return 4.2025;
            }
          } else {
            if (rainfall <= 450.7426) {
              return 3.8417;
            } else {
              return 4.3594;
            }
          }
        } else {
          if (temperature <= 24.9891) {
            if (humidity <= 88.5432) {
              return 3.5485;
            } else {
              return 2.8433;
            }
          } else {
            if (temperature <= 34.6087) {
              return 2.9757;
            } else {
              return 3.4310;
            }
          }
        }
      } else {
        if (temperature <= 20.0034) {
          if (month <= 9.5000) {
            if (rainfall <= 226.1388) {
              return 5.4503;
            } else {
              return 5.0265;
            }
          } else {
            if (rainfall <= 235.8185) {
              return 6.6125;
            } else {
              return 6.0404;
            }
          }
        } else {
          if (month <= 9.5000) {
            if (temperature <= 24.9774) {
              return 4.4046;
            } else {
              return 4.0027;
            }
          } else {
            if (temperature <= 34.7633) {
              return 4.6452;
            } else {
              return 5.2756;
            }
          }
        }
      }
    }
  }

}
